version: "3.8"
services:
  web:
    build: .
    ports:
      - "${FLASK_RUN_PORT}:${FLASK_RUN_PORT}"
    volumes:
      - .:/code
    environment:
      - FLASK_RUN_PORT
      - CAPACITY
      - EXPIRY
      - REDIS_HOST
      - REDIS_PORT
      - FLASK_ENV
      - MAX_CONN
  redis:
    image: "redis:alpine"
